language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: J15c7vw6FA1x6qmPcoPaXZn6ixMbEzek/TeUm6FFQlpNVYGQ/Kg/vfwBXfawxEUDTy+GjqolBzrjxtsKFY+mxnz1kfvyluAw8W9jSxtJ8jYfjN7Ta4OlqlzBiaw0li3VPOCV0e91cgP7JU6sARNZVtUNEudmoFwYyVERxgzlW0yPPRf82ymslHH4/Otwrr5sKQidBAmmTnXRO1L0XPStwkSd0sQJ93FigCuP14CkH/PnCLfBycabB9wVL4GPD+fE3VAOEd6cls5aVg7F2z05lEKlvhHn3n+7nRaGI1Z+fM6TsdJdg6KnCDce9L4fFzH7RqHmRXj8e57NjtABBONjSbCKhDNvk6NY6+1aq+ERFVNZYG56PHEN/iwxaZJoY97cx79d2BrFR9PwBBAdw7S4gboK1GElhDhLO/p2kKwgsIXbIAiMBi9bY9uUiXKhXtFZ2yY1LKmLGkmNlCpBHNgoiLis2mAfzdL8xbXGBmLoNu0/ByfOdIvQJXFzEqWKukw/LD1+m3RTaQfxcUNvWupJ1sazn9+LFI8wl6EtlMlSHxqdHrMGo40QeNpiBCbbuBbSK1wzfo3AdSM0+MjvVgCoU7hDU5+YSlzp6oJg1VZcvmaUmgLwaYd9aMQWA99xzI+S6swxy9W793gNq/ppGzmvd/wKo8qYYISrhFWmdYKfv7Q=
  app: react-trello-testing
  on:
    repo: Laurn17/react-trello-testing
