language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: BhTcS/Kp3xKjAfGlaymyWnqmYwAFBeQtvI8YpDOXQFzZJD7cCyDAMP5XJAHzghvrbdgOAQcPM7Eqe3FnhY35esPV05kWZfXFEJYcKH4+JvOfffTCGsmJbAB/5gP0HF4FHJkbLZyZrM6rdImjF6n4tnmk8iMV0kha2AEpcSYyk+1jlwi1Gwrs53VoDlXsz7X45tIiLjkzt+u++RFOiDNfxqEsmkd9A+7lvYXan/8wu8LvgYxIfOo0jBqPHyj56ZnRyAx82roTGUhPqvuqJT9LX+JaS0s5YYzH8D3sq7TEU1aLMlxun86USqNHUGEvECiFguayz4HZEr4V2v2WDBVPcil9ydWZIusZIhNjRYMmF+hbj2OAWhupoQzpfPb8bHFvEDqdOteUx3944wOswlW8Gp8mU8dZUiyO8zuECJfjvefy08DjkIueFGugrFznXNIphThBRdrCOKhA7CUNMN1NtRJ6zPUg5frZMHlfEJbnsk6YHEriBce5By4muOxOjwDESXAH2d+AQYtPNscYwyEVBprsJWkiZsmjxWLID2VyGD8FO4dJ457g1pQhGtGEk3HyChxOqu+76q7xhFuQnW+IJOvA9QVKCKNHeUd5KS73jRkJ1N7GJU3xBmjiVb81ugDBAu4q+axRLnt4d8txaQoxunUFn7iXMWtpB+t9E63jj5w=
  app: react-trello-testing
  on:
    repo: Laurn17/react-trello-testing
