language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: a6Rnw72TGdN78XuEEyvFUo9otDWaIrimxqO32phqNFpt7+OORCcKGvMImvO92Cffpb9hBr3JVnsqBF0ZrQutWg/UeoYw0BgRUy/LyO5J72CZlrgLyeaPXJZsuZw9aZ89Yxh9kFqesDlEQJ8H4mMHsQ+GW8xq+fgRW4O9kx2Oyc29kX1kOmnckOTHmQjDKKG/hQWEiweiSV5d1fD8GKMPBTiPX+ktCyIeawhhtTdy8fx3LgVx7cM3qS8IViwuGOMAkmMFqNTAI7XmfYDM3mqGPgj+uJLnY92bfD6tquLONCIfQdpdCuDiAT/TDK45MFTKwShFr23BRV1XLrgqAtOTl/e+2UrSkZr1rexZG7uyu2TMeFFHoIob25ggt8NCkNu977OU9toikHdIQbG4NAL7cQNJG+TduiAFsjTw0GhnorMwPyUtdMbcm/AQTZRuDcSVacB7RFki1bFmZyM1gexmoFL0hXl+ZuMjvvYVsJjLjszwVE/VPxFUWaVCCn1v/vWFJeG6Y8DTGFjCgcOfmprpYSkuQbrjX+rlK7918lg/ciVV5jzQHlj3l5fBwNZAaDamQdL/YeqNku1ROI0W/HLqSc/44j7O6qPN65Me89phMX5vGJUOGBp92n9q8aP9HV6Kz4mO87VSGoxZqCiR4XgtdndkwQ7b6Bgiqfa1DE/XL0E=
  app: react-trello-testing
  on:
    repo: Laurn17/react-trello-testing
