language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: RmxZZkVPcpxgYS4hnGoPBAMrXGcGabyHGa8365Zsp6xqPVoMxNkJxvsrQ7LVYr7gW7SrsjxzUymfv4o8ChZLxgLZmbYabtyOcY5QNEXNfiJwY/AAWO0jOl7/oyWeZlV0I8bjAY4RfNx8oib22sd8HwFe1TM92UVJfuliR/brM6pCaLjIRrDhc4+HFu/2j6POpnRAa0SGlZacuvgE02kYp5LU3ATUWtIbmFHAVuaiQxxbVlZVP6uPrvhI2Xss7xNcCxfIDrQ0urk/2lq6UsK+J/tDMpnVlRzOqnDjkjy22znNCfjOWjGO0Eln+OWNw+9yeugtBskxyYKAH/m7o6aVoW+w1zmrm6r6b+iSt3nI0RGPgzbb0l7Xz92LR8x4PAzd7K9ZYrzBmi/ETwbs/7Cq5SlDwQn5o7LUt634LtxqxelOTMMRFfpmfcgk/NrHPkamcXrO//ZyrTh98k+KaxUhytDolfRDQLMiu0uOn0gfGj3P303WJSJRGkDucTUmyhFZeIRl5zH3q3/MwoiYWYFYLxZB3g41GTjO7lKmaEQU6oOspxYTuVUn65lV2S07dg6voY6DZRvma6ozn2/zxGQ1kNlA0eusMpl/liSJe0NIaiFEC/S77lOrYw7Ab2GxNI6UKkBtlJyv+w+CKxgpv6rarfUk0lVyevFpX6joUfg1HCY=
  app: react-trello-testing
  on:
    repo: Laurn17/react-trello-testing
